name: Deploy .NET Application to Azure and Push to ACR

on:
  push:
    branches:
      - main  # Trigger the action when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can also use windows-latest if needed
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0'  # Specify the .NET version to use

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}  # The login server for ACR (e.g., <your-registry-name>.azurecr.io)
          username: ${{ secrets.ACR_USERNAME }}  # The ACR username (can be a service principal or admin)
          password: ${{ secrets.ACR_PASSWORD }}  # The ACR password or service principal password
      
      - name: SHA of the commit
        id: commit_sha
        run: |
          echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      
      - name: Build Docker image
        env: 
          IMAGE_TAG: ${{ steps.commit_sha.outputs.sha }}
          ACR_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER  }}  # The name of your ACR registry
        run: |
          docker build -f LanguageTranslation/Dockerfile  -t ${{ env.ACR_REGISTRY }}/language-translation${{env.IMAGE_TAG }}  -t ${{ ACR_REGISTRY }}/language-translation:latest .  # Build the image with the tag "latest"

      #  Push the Docker image to Azure Container Registry
      - name: Push Docker image to ACR
        run: |
          docker push ${{ env.ACR_REGISTRY }}/language-translation --all-tags # Push the image to ACR